using Blackbird.Applications.Sdk.Common.Dynamic;

namespace Apps.Smartcat.DataSourceHandlers;

public class LanguageDataHandler : IDataSourceHandler
{
    public Dictionary<string, string> GetData(DataSourceContext context)
    {
        var langs = new Dictionary<string, string>()
        {
            { "Abkhaz", "ab" }, { "Acholi", "ach-Latn" }, { "Afar", "aa" }, { "Afrikaans", "af" }, { "Akan", "ak" },
            { "Albanian", "sq" }, { "Amharic", "am" }, { "Angika", "anp-Deva" }, { "Arabic", "ar" },
            { "Arabic (Algeria)", "ar-DZ" }, { "Arabic (Bahrain)", "ar-BH" }, { "Arabic (Egypt)", "ar-EG" },
            { "Arabic (Iraq)", "ar-IQ" }, { "Arabic (Israel)", "ar-IL" }, { "Arabic (Jordan)", "ar-JO" },
            { "Arabic (Kuwait)", "ar-KW" }, { "Arabic (Lebanon)", "ar-LB" }, { "Arabic (Morocco)", "ar-MA" },
            { "Arabic (Qatar)", "ar-QA" }, { "Arabic (Saudi Arabia)", "ar-SA" }, { "Arabic (Sudan)", "ar-SD" },
            { "Arabic (UAE)", "ar-AE" }, { "Armenian", "hy" }, { "Armenian (Eastern)", "hy-arevela" },
            { "Armenian (Western)", "hy-arevmda" }, { "Assamese (Bengali)", "as" }, { "Assamese (Latin)", "as-Latn" },
            { "Assyrian Neo-Aramaic", "aii" }, { "Australian Kriol", "rop-Latn" }, { "Avar", "av" },
            { "Azerbaijani (Cyrillic)", "az-Cyrl" }, { "Azerbaijani (Latin)", "az-Latn" },
            { "Balochi (Southern)", "bcc" }, { "Bambara", "bm" }, { "Bashkir", "ba" }, { "Basque", "eu" },
            { "Bassa", "bsq-Latn" }, { "Beembe (Kibembe)", "beq" }, { "Belarusian", "be" }, { "Bemba", "bem-Latn" },
            { "Bengali", "bn" }, { "Bhojpuri", "bho-Deva" }, { "Bihari", "bh" }, { "Bislama", "bi-Latn" },
            { "Bodo", "brx-Deva" }, { "Bosnian", "bs" }, { "Bulgarian", "bg" }, { "Bulu (Bantu)", "bum" },
            { "Burmese", "my" }, { "Cape Verdean Creole", "kea" }, { "Catalan", "ca" }, { "Cebuano", "ceb" },
            { "Central Alaskan Yupʼik", "esu" }, { "Central-Eastern Arrernte", "aer-Latn" }, { "Chechen", "ce" },
            { "Chhattisgarhi (Devanagari)", "hne-Deva" }, { "Chhattisgarhi (Odia)", "hne-Orya" }, { "Chichewa", "ny" },
            { "Chinese (Cantonese)", "yue" }, { "Chinese (Pinyin)", "zh-Latn-pinyin" },
            { "Chinese (simplified)", "zh-Hans" }, { "Chinese (simplified, Malaysia)", "zh-Hans-MY" },
            { "Chinese (simplified, PRC)", "zh-Hans-CN" }, { "Chinese (simplified, Singapore)", "zh-Hans-SG" },
            { "Chinese (traditional)", "zh-Hant" }, { "Chinese (traditional, Hong Kong)", "zh-Hant-HK" },
            { "Chinese (traditional, Macau)", "zh-Hant-MO" }, { "Chinese (traditional, Taiwan)", "zh-Hant-TW" },
            { "Chittagonian (Arabic)", "ctg-Arab" }, { "Chittagonian (Bengali)", "ctg-Beng" },
            { "Chittagonian (Latin)", "ctg-Latn" }, { "Chokwe", "cjk-Latn" }, { "Chuj", "cac-Latn" },
            { "Chuukese", "chk-Latn" }, { "Chuvash", "cv" }, { "Cook Islands Māori", "rar" }, { "Cornish", "kw" },
            { "Croatian", "hr" }, { "Czech", "cs" }, { "Danish", "da" }, { "Dholuo", "luo-Latn" },
            { "Dhuwal", "dwu-Latn" }, { "Dinka", "din" }, { "Dogri (Arabic)", "doi-Arab" },
            { "Dogri (Devanagari)", "doi-Deva" }, { "Dogri (Dogri)", "doi-Dogr" }, { "Dutch", "nl" },
            { "Dutch (Aruba)", "nl-AW" }, { "Dutch (Belgium)", "nl-BE" },
            { "Dutch (Bonaire, Sint Eustatius and Saba)", "nl-BQ" }, { "Dutch (Curaçao)", "nl-CW" },
            { "Dutch (Netherlands)", "nl-NL" }, { "Dutch (Sint Maarten)", "nl-SX" }, { "Dutch (Suriname)", "nl-SR" },
            { "Dyula (Arabic)", "dyu-Arab" }, { "Dyula (Latin)", "dyu-Latn" }, { "Dyula (N'Ko)", "dyu-Nkoo" },
            { "Dzongkha", "dz" }, { "Eastern Kayah", "eky" }, { "English", "en" }, { "English (Australia)", "en-AU" },
            { "English (Canada)", "en-CA" }, { "English (India)", "en-IN" }, { "English (Ireland)", "en-IE" },
            { "English (New Zealand)", "en-NZ" }, { "English (Philippines)", "en-PH" },
            { "English (Singapore)", "en-SG" }, { "English (South Africa)", "en-ZA" },
            { "English (United Kingdom)", "en-GB" }, { "English (USA)", "en-US" }, { "Esperanto", "eo" },
            { "Estonian", "et" }, { "Ewe", "ee-Latn" }, { "Falam Chin", "cfm-Latn" }, { "Faroese", "fo" },
            { "Fijian", "fj" }, { "Filipino", "fil" }, { "Finnish", "fi" }, { "Fon", "fon-Latn" }, { "French", "fr" },
            { "French (Belgium)", "fr-BE" }, { "French (Cameroon)", "fr-CM" }, { "French (Canada)", "fr-CA" },
            { "French (France)", "fr-FR" }, { "French (Ghana)", "fr-GH" }, { "French (Ivory Coast)", "fr-CI" },
            { "French (Senegal)", "fr-SN" }, { "French (Switzerland)", "fr-CH" }, { "Fula", "ff" },
            { "Ga", "gaa-Latn" }, { "Galician", "gl" }, { "Ganda", "lg" }, { "Garo (Bengali)", "grt-Beng" },
            { "Garo (Latin)", "grt-Latn" }, { "Georgian", "ka" }, { "German", "de" }, { "German (Austria)", "de-AT" },
            { "German (Germany)", "de-DE" }, { "German (Switzerland)", "de-CH" }, { "Gilbertese", "gil-Latn" },
            { "Greek", "el" }, { "Greenlandic", "kl" }, { "Guarani", "gn" }, { "Gujarati", "gu" },
            { "Gusii (Arabic)", "guz-Arab" }, { "Gusii (Latin)", "guz-Latn" }, { "Haitian Creole", "ht" },
            { "Hakha Chin", "cnh-Latn" }, { "Hausa (Latin)", "ha-Latn" }, { "Hawaiian", "haw-Latn" },
            { "Hazaragi", "haz" }, { "Hebrew", "he" }, { "Herero", "hz" }, { "Hiligaynon", "hil-Latn" },
            { "Hindi", "hi" }, { "Hmong", "hmn" }, { "Hungarian", "hu" }, { "Icelandic", "is" }, { "Igbo", "ig" },
            { "Ikwere", "ikw" }, { "Ilocano", "ilo-Latn" }, { "Indonesian", "id" }, { "Ingush", "inh" },
            { "Irish", "ga" }, { "Italian", "it" }, { "Italian (Italy)", "it-IT" },
            { "Italian (Switzerland)", "it-CH" }, { "Iu Mien", "ium-Latn" }, { "Japanese", "ja" }, { "Javanese", "jv" },
            { "Jola", "dyo-Latn" }, { "Juba Arabic (Latin)", "pga-Latn" }, { "Kabardian", "kbd-Cyrl" },
            { "Kabyle", "kab" }, { "Kanauji", "bjj-Deva" }, { "Kannada", "kn" }, { "Kaonde", "kqn-Latn" },
            { "Karen", "kar-Mymr" }, { "Kashmiri (Arabic)", "ks-Arab" }, { "Kashmiri (Devanagari)", "ks-Deva" },
            { "Kazakh", "kk" }, { "Khasi", "kha-Beng" }, { "Khmer", "km" }, { "Kiga", "cgg-Latn" },
            { "Kikuyu", "ki-Latn" }, { "Kimbundu", "kmb-Latn" }, { "Kinyarwanda", "rw" }, { "Kirundi", "rn" },
            { "Komi", "kv" }, { "Konkani (Devanagari)", "kok" }, { "Konkani (Latin)", "kok-Latn" },
            { "Konzo", "koo-Latn" }, { "Korean", "ko" }, { "Krio", "kri" }, { "Kurdish (Kurmandji)", "kmr-Latn" },
            { "Kurdish (Palewani)", "sdh-Arab" }, { "Kurdish (Sorani)", "ckb-Arab" }, { "Kwanyama", "kj-Latn" },
            { "Kyrgyz", "ky" }, { "Kʼicheʼ", "quc-Latn" }, { "Lamba", "lam-Latn" }, { "Lango", "laj-Latn" },
            { "Lao", "lo" }, { "Latin", "la" }, { "Latvian", "lv" }, { "Lenje", "leh-Latn" }, { "Limburgish", "li" },
            { "Lingala", "ln" }, { "Lithuanian", "lt" }, { "Lozi", "loz" }, { "Luba-Kasai", "lua-Latn" },
            { "Luchazi", "lch-Latn" }, { "Luhya", "luy-Latn" }, { "Lunda", "lun-Latn" }, { "Luvale", "lue-Latn" },
            { "Luxembourgish", "lb" }, { "Maasai", "mas-Latn" }, { "Maca", "mca" }, { "Macedonian", "mk" },
            { "Madurese (Arabic)", "mad-Arab" }, { "Madurese (Javanese)", "mad-Java" },
            { "Madurese (Latin)", "mad-Latn" }, { "Magahi", "mag-Deva" }, { "Maithili", "mai" },
            { "Makhuwa", "vmw-Latn" }, { "Malagasy", "mg" }, { "Malay", "ms" }, { "Malay (Malaysia)", "ms-MY" },
            { "Malay (Singapore)", "ms-SG" }, { "Malayalam", "ml" }, { "Maltese", "mt" }, { "Mam", "mam-Latn" },
            { "Mandinka (Arabic)", "mnk-Arab" }, { "Mandinka (Latin)", "mnk-Latn" }, { "Mandinka (N'Ko)", "mnk-Nkoo" },
            { "Maori", "mi" }, { "Marathi", "mr" }, { "Mari", "mhr" }, { "Marshallese", "mh" },
            { "Meitei (Bengali)", "mni-Beng" }, { "Meitei (Latin)", "mni-Latn" }, { "Meitei (Meitei)", "mni-Mtei" },
            { "Mizo", "lus-Latn" }, { "Mongolian", "mn" }, { "Montenegrin", "cnr-Latn" },
            { "Mooré (Latin)", "mos-Latn" }, { "Mooré (N'Ko)", "mos-Nkoo" }, { "Nagpuri", "sck-Deva" },
            { "Navaho", "nv-Latn" }, { "Ndonga", "ng-Latn" }, { "Nepali", "ne" }, { "Nigerian Pidgin", "pcm" },
            { "Niuean", "niu" }, { "Nkore", "nyn-Latn" }, { "Northern Ndebele", "nd" }, { "Northern Sotho", "nso" },
            { "Norwegian", "no" }, { "Norwegian (Bokmål)", "nb" }, { "Norwegian (Nynorsk)", "nn" }, { "Nuer", "nus" },
            { "Nyoro", "nyo-Latn" }, { "Occitan", "oc" }, { "Odia", "or" }, { "Oromo", "om" }, { "Ossetian", "os" },
            { "Papiamento", "pap" }, { "Papiamento (Aruba)", "pap-AW" },
            { "Papiamentu (Bonaire, Sint Eustatius and Saba)", "pap-BQ" }, { "Papiamentu (Curaçao)", "pap-CW" },
            { "Pashto", "ps" }, { "Persian", "fa" }, { "Persian (Afghanistan) / Dari", "fa-AF" },
            { "Persian (Iran)", "fa-IR" }, { "Pijin", "pis-Latn" }, { "Pitjantjatjara", "pjt-Latn" },
            { "Pohnpeian", "pon-Latn" }, { "Polish", "pl" }, { "Portuguese", "pt" }, { "Portuguese (Brazil)", "pt-BR" },
            { "Portuguese (Portugal)", "pt-PT" }, { "Pulaar (Adlam)", "fuc-Adlm" }, { "Pulaar (Arabic)", "fuc-Arab" },
            { "Pulaar (Latin)", "fuc-Latn" }, { "Punjabi (Gurmukhi)", "pa" }, { "Punjabi (Shahmukhi)", "pa-Arab" },
            { "Qʼeqchiʼ", "kek-Latn" }, { "Rangi", "lag-Latn" }, { "Rohingya (Hanifi)", "rhg-Rohg" },
            { "Rohingya (Latin)", "rhg-Latn" }, { "Romanian", "ro" }, { "Romanian (Moldova)", "ro-MD" },
            { "Romanian (Romania)", "ro-RO" }, { "Rongmei (Latin)", "nbu-Latn" }, { "Rongmei (Meitei)", "nbu-Mtei" },
            { "Russian", "ru" }, { "Russian (Belarus)", "ru-BY" }, { "Russian (Kazakhstan)", "ru-KZ" },
            { "Russian (Russia)", "ru-RU" }, { "S'gaw Karen (Burmese)", "ksw-Mymr" },
            { "S'gaw Karen (Latin)", "ksw-Latn" }, { "Sakha", "sah" }, { "Samoan", "sm" }, { "Sango", "sg" },
            { "Sanskrit", "sa" }, { "Santali (Bengali)", "sat-Beng" }, { "Santali (Latin)", "sat-Latn" },
            { "Santali (Odia)", "sat-Orya" }, { "Santali (Ol Chiki)", "sat-Olck" }, { "Saraiki", "skr-Arab" },
            { "Sardinian", "sc" }, { "Scottish Gaelic", "gd-Latn" }, { "Serbian (Cyrillic)", "sr-Cyrl" },
            { "Serbian (Latin)", "sr-Latn" }, { "Serer", "srr-Latn" }, { "Sesotho", "st" }, { "Shan", "shn-Mymr" },
            { "Shona", "sn" }, { "Sindhi", "sd" }, { "Sinhalese", "si" }, { "Slovak", "sk" }, { "Slovenian", "sl" },
            { "Somali", "so" }, { "Southern Ndebele", "nr" }, { "Spanish", "es" }, { "Spanish (Argentina)", "es-AR" },
            { "Spanish (Chile)", "es-CL" }, { "Spanish (Colombia)", "es-CO" }, { "Spanish (Guatemala)", "es-GT" },
            { "Spanish (Latin America)", "es-419" }, { "Spanish (Mexico)", "es-MX" },
            { "Spanish (Nicaragua)", "es-NI" }, { "Spanish (Peru)", "es-PE" }, { "Spanish (Puerto Rico)", "es-PR" },
            { "Spanish (Spain)", "es-ES" }, { "Spanish (USA)", "es-US" }, { "Sundanese", "su" }, { "Susu", "sus" },
            { "Swahili", "sw" }, { "Swati", "ss" }, { "Swedish", "sv" }, { "Tagalog", "tl" }, { "Tajik", "tg" },
            { "Tamil", "ta" }, { "Tatar", "tt" }, { "Tedim Chin", "ctd-Latn" }, { "Telugu", "te" }, { "Tetum", "tet" },
            { "Thai", "th" }, { "Tibetan", "bo" }, { "Tigrinya", "ti" }, { "Tiwi", "tiw-Latn" },
            { "Tonga", "toi-Latn" }, { "Tongan", "to" }, { "Tooro", "ttj-Latn" },
            { "Torres Strait Creole", "tcs-Latn" }, { "Tsonga", "ts" }, { "Tswana", "tn" }, { "Turkish", "tr" },
            { "Turkmen", "tk" }, { "Twi", "tw-Latn" }, { "Udmurt", "udm" }, { "Ukrainian", "uk" }, { "Urdu", "ur" },
            { "Uyghur", "ug" }, { "Uzbek (Cyrillic)", "uz-Cyrl" }, { "Uzbek (Latin)", "uz-Latn" }, { "Venda", "ve" },
            { "Vietnamese", "vi" }, { "Vlax Romani (Cyrillic)", "rmy-Cyrl" }, { "Vlax Romani (Latin)", "rmy-Latn" },
            { "Warlpiri", "wbp-Latn" }, { "Welsh", "cy" }, { "Western Arrernte", "are-Latn" }, { "Wolof", "wo" },
            { "Xhosa", "xh" }, { "Yiddish", "yi" }, { "Yoruba", "yo" }, { "Zulu", "zu" }
        };

        return langs.Where(x =>
                context.SearchString is null ||
                x.Value.Contains(context.SearchString, StringComparison.OrdinalIgnoreCase))
            .Take(50)
            .ToDictionary(x => x.Key, x => x.Value);
    }
}